
FROM python:3.7-slim-buster
RUN apt-get update
RUN apt-get install git -y


# FROM python:3.7-alpine
# RUN apk update
# RUN apk add git

RUN pip install --upgrade pip
WORKDIR /project/
#ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache
RUN apt-get install gcc -y
# RUN pip3 install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.6.0-cp37-cp37m-manylinux2010_x86_64.whl
RUN pip3 install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.15.2-cp37-cp37m-manylinux2010_x86_64.whl

# torch-1.9.1-cp37-cp37m-manylinux1_x86_64.whl
WORKDIR /breaker/

RUN git clone https://github.com/kozzion/breaker_core
RUN git clone https://github.com/kozzion/breaker_aws
RUN git clone https://github.com/kozzion/breaker_audio


WORKDIR /breaker/breaker_core
RUN git pull
RUN pip3 install -e .

# RUN pip3 install -r requirements.txt
WORKDIR /breaker/breaker_audio
RUN git pull
RUN pip3 install -e .

WORKDIR /breaker/breaker_aws
RUN git pull
RUN pip3 install -e .
# RUN pip3 install -r requirements.txt

# TODO move up
RUN apt-get install libsndfile1 -y 
RUN apt-get install tk -y
RUN apt-get install libportaudio2 -y
RUN apt-get install wget -y

# TODO download and unzip models
WORKDIR /data/data_breaker
COPY model model
WORKDIR /data/data_breaker/model
RUN ls
# RUN wget https://drive.google.com/file/d/1NIz4I4eFBgOMI7BsdHaigCB1RTDnJmKO/view
# RUN wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=FILEID' -O FILENAME

# pip install gdown

# copy config
WORKDIR /breaker/breaker_audio/service
COPY config.cfg config.cfg
CMD [ "python3", "service_synthesize.py"]