
FROM python:3.7-slim-buster
RUN apt-get update
RUN apt-get install git -y


# FROM python:3.7-alpine
# RUN apk update
# RUN apk add git

RUN pip install --upgrade pip
WORKDIR /project/
#ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache
RUN git clone https://github.com/kozzion/breaker_core
RUN git clone https://github.com/kozzion/breaker_aws
RUN git clone https://github.com/kozzion/breaker_audio


RUN apt-get install gcc -y
# RUN pip3 install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.6.0-cp37-cp37m-manylinux2010_x86_64.whl
RUN pip3 install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.15.2-cp37-cp37m-manylinux2010_x86_64.whl

# torch-1.9.1-cp37-cp37m-manylinux1_x86_64.whl

WORKDIR /project/breaker_audio
RUN pip3 install -e .

WORKDIR /project/breaker_core
RUN pip3 install -e .
RUN git pull
# RUN pip3 install -r requirements.txt

WORKDIR /project/breaker_aws
RUN pip3 install -e .
RUN git pull
# RUN pip3 install -r requirements.txt

# TODO download and unzip models
WORKDIR /data/data_breaker





# copy config
WORKDIR /project/breaker_audio/service
COPY config.cfg config.cfg
CMD [ "python3", "service_synthesize"]